import type {
  Conversation,
  Customer,
  Notification,
  Order,
  Product,
  TeamMember,
  User,
} from "./types"

export const currentUser: User = {
  id: "u1",
  name: "Maria Garcia",
  email: "maria@acmecorp.com",
  role: "admin",
  status: "online",
  lastSeen: "2026-02-06T10:00:00Z",
}

export const conversations: Conversation[] = [
  {
    id: "c1",
    customerName: "Carlos Mendez",
    customerPhone: "+1 555-0101",
    status: "open",
    mode: "ai",
    assignedAgent: undefined,
    priority: "high",
    labels: ["vip", "urgent"],
    lastMessage: "I need help with my order #1042, it hasn't arrived yet.",
    lastMessageAt: "2026-02-06T09:45:00Z",
    unreadCount: 3,
    messages: [
      { id: "m1", sender: "customer", senderName: "Carlos Mendez", content: "Hello, I placed an order 3 days ago.", timestamp: "2026-02-06T09:30:00Z" },
      { id: "m2", sender: "ai", senderName: "AI Assistant", content: "Hi Carlos! I'd be happy to help. Could you please share your order number?", timestamp: "2026-02-06T09:31:00Z" },
      { id: "m3", sender: "customer", senderName: "Carlos Mendez", content: "It's order #1042.", timestamp: "2026-02-06T09:33:00Z" },
      { id: "m4", sender: "ai", senderName: "AI Assistant", content: "I found your order #1042. It was shipped on Feb 4th. Let me check the tracking status.", timestamp: "2026-02-06T09:34:00Z" },
      { id: "m5", sender: "customer", senderName: "Carlos Mendez", content: "I need help with my order #1042, it hasn't arrived yet.", timestamp: "2026-02-06T09:45:00Z" },
    ],
  },
  {
    id: "c2",
    customerName: "Ana Torres",
    customerPhone: "+1 555-0102",
    status: "open",
    mode: "human",
    assignedAgent: "u1",
    priority: "medium",
    labels: ["returns"],
    lastMessage: "Thank you, I'll wait for the return label.",
    lastMessageAt: "2026-02-06T09:30:00Z",
    unreadCount: 0,
    messages: [
      { id: "m6", sender: "customer", senderName: "Ana Torres", content: "I'd like to return a product I bought last week.", timestamp: "2026-02-06T08:00:00Z" },
      { id: "m7", sender: "ai", senderName: "AI Assistant", content: "I understand you'd like to process a return. Let me connect you with an agent who can help.", timestamp: "2026-02-06T08:01:00Z" },
      { id: "m8", sender: "system", senderName: "System", content: "Conversation taken over by Maria Garcia", timestamp: "2026-02-06T08:05:00Z" },
      { id: "m9", sender: "human", senderName: "Maria Garcia", content: "Hi Ana! I'll process your return right away. I'm sending you a return label via email.", timestamp: "2026-02-06T08:10:00Z" },
      { id: "m10", sender: "customer", senderName: "Ana Torres", content: "Thank you, I'll wait for the return label.", timestamp: "2026-02-06T09:30:00Z" },
    ],
  },
  {
    id: "c3",
    customerName: "Roberto Silva",
    customerPhone: "+1 555-0103",
    status: "pending",
    mode: "ai",
    priority: "low",
    labels: [],
    lastMessage: "What are your store hours?",
    lastMessageAt: "2026-02-06T08:15:00Z",
    unreadCount: 1,
    messages: [
      { id: "m11", sender: "customer", senderName: "Roberto Silva", content: "What are your store hours?", timestamp: "2026-02-06T08:15:00Z" },
      { id: "m12", sender: "ai", senderName: "AI Assistant", content: "Our store is open Monday through Friday from 9 AM to 6 PM, and Saturdays from 10 AM to 4 PM.", timestamp: "2026-02-06T08:15:30Z" },
    ],
  },
  {
    id: "c4",
    customerName: "Laura Martinez",
    customerPhone: "+1 555-0104",
    status: "closed",
    mode: "ai",
    priority: "medium",
    labels: ["feedback"],
    lastMessage: "Great, thanks for your help!",
    lastMessageAt: "2026-02-05T16:30:00Z",
    unreadCount: 0,
    messages: [
      { id: "m13", sender: "customer", senderName: "Laura Martinez", content: "Is the premium plan worth it?", timestamp: "2026-02-05T16:00:00Z" },
      { id: "m14", sender: "ai", senderName: "AI Assistant", content: "The premium plan includes priority support, advanced analytics, and unlimited integrations. It's great for growing businesses.", timestamp: "2026-02-05T16:01:00Z" },
      { id: "m15", sender: "customer", senderName: "Laura Martinez", content: "Great, thanks for your help!", timestamp: "2026-02-05T16:30:00Z" },
    ],
  },
  {
    id: "c5",
    customerName: "Diego Fernandez",
    customerPhone: "+1 555-0105",
    status: "open",
    mode: "ai",
    priority: "urgent",
    labels: ["billing", "urgent"],
    lastMessage: "I was charged twice for the same order!",
    lastMessageAt: "2026-02-06T10:00:00Z",
    unreadCount: 2,
    messages: [
      { id: "m16", sender: "customer", senderName: "Diego Fernandez", content: "I was charged twice for the same order!", timestamp: "2026-02-06T10:00:00Z" },
      { id: "m17", sender: "ai", senderName: "AI Assistant", content: "I'm sorry about that! Let me look into your account right away.", timestamp: "2026-02-06T10:00:30Z" },
    ],
  },
  {
    id: "c6",
    customerName: "Patricia Gomez",
    customerPhone: "+1 555-0106",
    status: "open",
    mode: "human",
    assignedAgent: "u2",
    priority: "high",
    labels: ["technical"],
    lastMessage: "The app keeps crashing when I try to checkout.",
    lastMessageAt: "2026-02-06T09:55:00Z",
    unreadCount: 1,
    messages: [
      { id: "m18", sender: "customer", senderName: "Patricia Gomez", content: "The app keeps crashing when I try to checkout.", timestamp: "2026-02-06T09:50:00Z" },
      { id: "m19", sender: "system", senderName: "System", content: "Conversation assigned to Juan Lopez", timestamp: "2026-02-06T09:51:00Z" },
      { id: "m20", sender: "human", senderName: "Juan Lopez", content: "Hi Patricia, I'm looking into this issue. Can you tell me what device you're using?", timestamp: "2026-02-06T09:55:00Z" },
    ],
  },
]

export const orders: Order[] = [
  {
    id: "ORD-1042",
    customerName: "Carlos Mendez",
    customerPhone: "+1 555-0101",
    customerEmail: "carlos@email.com",
    deliveryAddress: "123 Main St, Apt 4B, New York, NY 10001",
    notes: "Leave at the door please",
    paymentMethod: "card",
    items: [
      { name: "Wireless Headphones Pro", quantity: 1, price: 89.99 },
      { name: "USB-C Charging Cable", quantity: 2, price: 12.99 },
    ],
    total: 115.97,
    status: "delivering",
    paymentStatus: "paid",
    conversationId: "c1",
    createdAt: "2026-02-03T14:00:00Z",
  },
  {
    id: "ORD-1041",
    customerName: "Ana Torres",
    customerPhone: "+1 555-0102",
    customerEmail: "ana@email.com",
    deliveryAddress: "456 Oak Ave, Suite 12, Los Angeles, CA 90001",
    notes: "",
    paymentMethod: "card",
    items: [{ name: "Smart Watch Band", quantity: 1, price: 29.99 }],
    total: 29.99,
    status: "completed",
    paymentStatus: "paid",
    conversationId: "c2",
    createdAt: "2026-02-01T10:00:00Z",
  },
  {
    id: "ORD-1043",
    customerName: "Diego Fernandez",
    customerPhone: "+1 555-0105",
    customerEmail: "diego@email.com",
    deliveryAddress: "789 Pine Rd, Chicago, IL 60601",
    notes: "Call before delivery",
    paymentMethod: "transfer",
    items: [
      { name: "Bluetooth Speaker Mini", quantity: 1, price: 49.99 },
      { name: "Phone Case Premium", quantity: 1, price: 24.99 },
    ],
    total: 74.98,
    status: "new",
    paymentStatus: "paid",
    conversationId: "c5",
    createdAt: "2026-02-06T08:00:00Z",
  },
  {
    id: "ORD-1044",
    customerName: "Patricia Gomez",
    customerPhone: "+1 555-0106",
    customerEmail: "patricia@email.com",
    deliveryAddress: "321 Elm Blvd, Houston, TX 77001",
    notes: "",
    paymentMethod: "card",
    items: [{ name: "Laptop Stand Adjustable", quantity: 1, price: 59.99 }],
    total: 59.99,
    status: "confirmed",
    paymentStatus: "paid",
    createdAt: "2026-02-05T15:00:00Z",
  },
  {
    id: "ORD-1045",
    customerName: "Laura Martinez",
    customerPhone: "+1 555-0104",
    customerEmail: "laura@email.com",
    deliveryAddress: "654 Maple Dr, Miami, FL 33101",
    notes: "Gift wrapping requested",
    paymentMethod: "cash",
    items: [
      { name: "Webcam HD 1080p", quantity: 1, price: 69.99 },
      { name: "Ring Light", quantity: 1, price: 34.99 },
    ],
    total: 104.98,
    status: "preparing",
    paymentStatus: "paid",
    createdAt: "2026-02-06T07:30:00Z",
  },
  {
    id: "ORD-1046",
    customerName: "Roberto Silva",
    customerPhone: "+1 555-0103",
    customerEmail: "roberto@email.com",
    deliveryAddress: "987 Cedar Ln, Seattle, WA 98101",
    notes: "",
    paymentMethod: "transfer",
    items: [{ name: "Mechanical Keyboard", quantity: 1, price: 129.99 }],
    total: 129.99,
    status: "canceled",
    paymentStatus: "failed",
    createdAt: "2026-02-04T12:00:00Z",
  },
  {
    id: "ORD-1047",
    customerName: "Sofia Herrera",
    customerPhone: "+1 555-0107",
    customerEmail: "sofia@email.com",
    deliveryAddress: "147 Birch St, Denver, CO 80201",
    notes: "Fragile items, handle with care",
    paymentMethod: "card",
    items: [{ name: "Desk Organizer Set", quantity: 2, price: 19.99 }],
    total: 39.98,
    status: "ready",
    paymentStatus: "paid",
    createdAt: "2026-02-06T06:00:00Z",
  },
]

export const products: Product[] = [
  { id: "p1", name: "Wireless Headphones Pro", price: 89.99, type: "physical", stock: 45, active: true },
  { id: "p2", name: "USB-C Charging Cable", price: 12.99, type: "physical", stock: 230, active: true },
  { id: "p3", name: "Smart Watch Band", price: 29.99, type: "physical", stock: 78, active: true },
  { id: "p4", name: "Bluetooth Speaker Mini", price: 49.99, type: "physical", stock: 3, active: true },
  { id: "p5", name: "Phone Case Premium", price: 24.99, type: "physical", stock: 156, active: true },
  { id: "p6", name: "Laptop Stand Adjustable", price: 59.99, type: "physical", stock: 22, active: true },
  { id: "p7", name: "Webcam HD 1080p", price: 69.99, type: "physical", stock: 0, active: false },
  { id: "p8", name: "Ring Light", price: 34.99, type: "physical", stock: 67, active: true },
  { id: "p9", name: "Mechanical Keyboard", price: 129.99, type: "physical", stock: 12, active: true },
  { id: "p10", name: "Desk Organizer Set", price: 19.99, type: "physical", stock: 89, active: true },
  { id: "p11", name: "Software License - Pro", price: 199.99, type: "digital", stock: 9999, active: true },
  { id: "p12", name: "Setup Consultation", price: 149.99, type: "service", stock: 9999, active: true },
]

export const customers: Customer[] = [
  { id: "cu1", name: "Carlos Mendez", phone: "+1 555-0101", email: "carlos@email.com", tags: ["vip", "frequent"], notes: "Prefers email communication", lastContact: "2026-02-06T09:45:00Z", conversationCount: 8, orderCount: 5 },
  { id: "cu2", name: "Ana Torres", phone: "+1 555-0102", email: "ana@email.com", tags: ["returns"], notes: "Returning customer", lastContact: "2026-02-06T09:30:00Z", conversationCount: 3, orderCount: 2 },
  { id: "cu3", name: "Roberto Silva", phone: "+1 555-0103", email: "roberto@email.com", tags: [], notes: "", lastContact: "2026-02-06T08:15:00Z", conversationCount: 1, orderCount: 1 },
  { id: "cu4", name: "Laura Martinez", phone: "+1 555-0104", email: "laura@email.com", tags: ["feedback"], notes: "Interested in premium plan", lastContact: "2026-02-05T16:30:00Z", conversationCount: 4, orderCount: 3 },
  { id: "cu5", name: "Diego Fernandez", phone: "+1 555-0105", email: "diego@email.com", tags: ["billing"], notes: "Needs billing resolution", lastContact: "2026-02-06T10:00:00Z", conversationCount: 2, orderCount: 2 },
  { id: "cu6", name: "Patricia Gomez", phone: "+1 555-0106", email: "patricia@email.com", tags: ["technical"], notes: "App issues reported", lastContact: "2026-02-06T09:55:00Z", conversationCount: 5, orderCount: 4 },
  { id: "cu7", name: "Sofia Herrera", phone: "+1 555-0107", email: "sofia@email.com", tags: ["new"], notes: "First-time customer", lastContact: "2026-02-06T06:00:00Z", conversationCount: 1, orderCount: 1 },
]

export const teamMembers: TeamMember[] = [
  { id: "u1", name: "Maria Garcia", email: "maria@acmecorp.com", role: "admin", status: "online", lastSeen: "2026-02-06T10:00:00Z", invitedAt: "2025-01-15T00:00:00Z" },
  { id: "u2", name: "Juan Lopez", email: "juan@acmecorp.com", role: "operator", status: "online", lastSeen: "2026-02-06T09:50:00Z", invitedAt: "2025-03-20T00:00:00Z" },
  { id: "u3", name: "Elena Rodriguez", email: "elena@acmecorp.com", role: "operator", status: "away", lastSeen: "2026-02-06T08:30:00Z", invitedAt: "2025-06-10T00:00:00Z" },
  { id: "u4", name: "Pedro Sanchez", email: "pedro@acmecorp.com", role: "operator", status: "offline", lastSeen: "2026-02-05T18:00:00Z", invitedAt: "2025-09-01T00:00:00Z" },
]

export const notifications: Notification[] = [
  { id: "n1", type: "chat", title: "New urgent chat", message: "Diego Fernandez reported a double charge issue", read: false, createdAt: "2026-02-06T10:00:00Z" },
  { id: "n2", type: "order", title: "New order received", message: "Order #1043 from Diego Fernandez - $74.98", read: false, createdAt: "2026-02-06T08:00:00Z" },
  { id: "n3", type: "stock", title: "Low stock alert", message: "Bluetooth Speaker Mini has only 3 units left", read: false, createdAt: "2026-02-06T07:00:00Z" },
  { id: "n4", type: "order", title: "Order ready for delivery", message: "Order #1047 for Sofia Herrera is ready", read: true, createdAt: "2026-02-06T06:30:00Z" },
  { id: "n5", type: "system", title: "System update", message: "AI model updated to version 3.2 - improved response accuracy", read: true, createdAt: "2026-02-05T22:00:00Z" },
  { id: "n6", type: "chat", title: "Chat handoff completed", message: "Conversation with Ana Torres transferred to human agent", read: true, createdAt: "2026-02-06T08:05:00Z" },
]
